package com.hbnu.mooc.dao;

import com.hbnu.mooc.bean.ClassCourse;
import com.hbnu.mooc.bean.ClassCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    long countByExample(ClassCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    int deleteByExample(ClassCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    int insert(ClassCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    int insertSelective(ClassCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    List<ClassCourse> selectByExample(ClassCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") ClassCourse record, @Param("example") ClassCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_course
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    int updateByExample(@Param("record") ClassCourse record, @Param("example") ClassCourseExample example);

	String selectClassId(String courseId);
}