package com.hbnu.mooc.dao;

import com.hbnu.mooc.bean.TeacherCourse;
import com.hbnu.mooc.bean.TeacherCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    long countByExample(TeacherCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    int deleteByExample(TeacherCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    int insert(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    int insertSelective(TeacherCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    List<TeacherCourse> selectByExample(TeacherCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") TeacherCourse record, @Param("example") TeacherCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    int updateByExample(@Param("record") TeacherCourse record, @Param("example") TeacherCourseExample example);
    
    List<String> selectCourseId(String teac);
}