package com.hbnu.mooc.bean;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Admin_NO
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String adminNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.User_ID_A
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String userIdA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Name
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Create_time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Creator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Updator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String updator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Admin_NO
     *
     * @return the value of admin.Admin_NO
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getAdminNo() {
        return adminNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Admin_NO
     *
     * @param adminNo the value for admin.Admin_NO
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setAdminNo(String adminNo) {
        this.adminNo = adminNo == null ? null : adminNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.User_ID_A
     *
     * @return the value of admin.User_ID_A
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getUserIdA() {
        return userIdA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.User_ID_A
     *
     * @param userIdA the value for admin.User_ID_A
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setUserIdA(String userIdA) {
        this.userIdA = userIdA == null ? null : userIdA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Name
     *
     * @return the value of admin.Name
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Name
     *
     * @param name the value for admin.Name
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Create_time
     *
     * @return the value of admin.Create_time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Create_time
     *
     * @param createTime the value for admin.Create_time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Creator
     *
     * @return the value of admin.Creator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Creator
     *
     * @param creator the value for admin.Creator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Update_Time
     *
     * @return the value of admin.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Update_Time
     *
     * @param updateTime the value for admin.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Updator
     *
     * @return the value of admin.Updator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Updator
     *
     * @param updator the value for admin.Updator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }
}