package com.hbnu.mooc.bean;

import java.util.Date;

public class Chapter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.chapter_id
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.chapter_content
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String chapterContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.course_id
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.weight
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.Create_time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.Creator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.Updator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String updator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.Video_Path
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String videoPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.work_path
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private String workPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.chapter_index
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    private Integer chapterIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.chapter_id
     *
     * @return the value of chapter.chapter_id
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.chapter_id
     *
     * @param chapterId the value for chapter.chapter_id
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setChapterId(String chapterId) {
        this.chapterId = chapterId == null ? null : chapterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.chapter_content
     *
     * @return the value of chapter.chapter_content
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getChapterContent() {
        return chapterContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.chapter_content
     *
     * @param chapterContent the value for chapter.chapter_content
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setChapterContent(String chapterContent) {
        this.chapterContent = chapterContent == null ? null : chapterContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.course_id
     *
     * @return the value of chapter.course_id
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.course_id
     *
     * @param courseId the value for chapter.course_id
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.weight
     *
     * @return the value of chapter.weight
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.weight
     *
     * @param weight the value for chapter.weight
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.Create_time
     *
     * @return the value of chapter.Create_time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.Create_time
     *
     * @param createTime the value for chapter.Create_time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.Creator
     *
     * @return the value of chapter.Creator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.Creator
     *
     * @param creator the value for chapter.Creator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.Update_Time
     *
     * @return the value of chapter.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.Update_Time
     *
     * @param updateTime the value for chapter.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.Updator
     *
     * @return the value of chapter.Updator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.Updator
     *
     * @param updator the value for chapter.Updator
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.Video_Path
     *
     * @return the value of chapter.Video_Path
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getVideoPath() {
        return videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.Video_Path
     *
     * @param videoPath the value for chapter.Video_Path
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setVideoPath(String videoPath) {
        this.videoPath = videoPath == null ? null : videoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.work_path
     *
     * @return the value of chapter.work_path
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public String getWorkPath() {
        return workPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.work_path
     *
     * @param workPath the value for chapter.work_path
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setWorkPath(String workPath) {
        this.workPath = workPath == null ? null : workPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.chapter_index
     *
     * @return the value of chapter.chapter_index
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public Integer getChapterIndex() {
        return chapterIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.chapter_index
     *
     * @param chapterIndex the value for chapter.chapter_index
     *
     * @mbg.generated Thu Sep 20 16:17:59 CST 2018
     */
    public void setChapterIndex(Integer chapterIndex) {
        this.chapterIndex = chapterIndex;
    }
}