package com.hbnu.mooc.bean;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.replay_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String replayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.topic_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.replay_content
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String replayContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Create_time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Creator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Updator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String updator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.replay_id
     *
     * @return the value of comment.replay_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getReplayId() {
        return replayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.replay_id
     *
     * @param replayId the value for comment.replay_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setReplayId(String replayId) {
        this.replayId = replayId == null ? null : replayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.topic_id
     *
     * @return the value of comment.topic_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.topic_id
     *
     * @param topicId the value for comment.topic_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setTopicId(String topicId) {
        this.topicId = topicId == null ? null : topicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.replay_content
     *
     * @return the value of comment.replay_content
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getReplayContent() {
        return replayContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.replay_content
     *
     * @param replayContent the value for comment.replay_content
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setReplayContent(String replayContent) {
        this.replayContent = replayContent == null ? null : replayContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.Create_time
     *
     * @return the value of comment.Create_time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.Create_time
     *
     * @param createTime the value for comment.Create_time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.Creator
     *
     * @return the value of comment.Creator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.Creator
     *
     * @param creator the value for comment.Creator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.Update_Time
     *
     * @return the value of comment.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.Update_Time
     *
     * @param updateTime the value for comment.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.Updator
     *
     * @return the value of comment.Updator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.Updator
     *
     * @param updator the value for comment.Updator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }
}