package com.hbnu.mooc.bean;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.stu_no
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String stuNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.paper_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String paperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.question_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.answer
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_id
     *
     * @return the value of record.record_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_id
     *
     * @param recordId the value for record.record_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.stu_no
     *
     * @return the value of record.stu_no
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.stu_no
     *
     * @param stuNo the value for record.stu_no
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setStuNo(String stuNo) {
        this.stuNo = stuNo == null ? null : stuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.paper_id
     *
     * @return the value of record.paper_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.paper_id
     *
     * @param paperId the value for record.paper_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setPaperId(String paperId) {
        this.paperId = paperId == null ? null : paperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.question_id
     *
     * @return the value of record.question_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.question_id
     *
     * @param questionId the value for record.question_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId == null ? null : questionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.answer
     *
     * @return the value of record.answer
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.answer
     *
     * @param answer the value for record.answer
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}