package com.hbnu.mooc.bean;

import java.util.Date;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Teacher_NO
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String teacherNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.User_ID_T
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String userIdT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Name
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Colleage_Name
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String colleageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Subject_Name
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String subjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Class_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.phone
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.sex
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Create_time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Creator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Updator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String updator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Teacher_NO
     *
     * @return the value of teacher.Teacher_NO
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getTeacherNo() {
        return teacherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Teacher_NO
     *
     * @param teacherNo the value for teacher.Teacher_NO
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setTeacherNo(String teacherNo) {
        this.teacherNo = teacherNo == null ? null : teacherNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.User_ID_T
     *
     * @return the value of teacher.User_ID_T
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getUserIdT() {
        return userIdT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.User_ID_T
     *
     * @param userIdT the value for teacher.User_ID_T
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setUserIdT(String userIdT) {
        this.userIdT = userIdT == null ? null : userIdT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Name
     *
     * @return the value of teacher.Name
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Name
     *
     * @param name the value for teacher.Name
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Colleage_Name
     *
     * @return the value of teacher.Colleage_Name
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getColleageName() {
        return colleageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Colleage_Name
     *
     * @param colleageName the value for teacher.Colleage_Name
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setColleageName(String colleageName) {
        this.colleageName = colleageName == null ? null : colleageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Subject_Name
     *
     * @return the value of teacher.Subject_Name
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Subject_Name
     *
     * @param subjectName the value for teacher.Subject_Name
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Class_id
     *
     * @return the value of teacher.Class_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Class_id
     *
     * @param classId the value for teacher.Class_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.phone
     *
     * @return the value of teacher.phone
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.phone
     *
     * @param phone the value for teacher.phone
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.sex
     *
     * @return the value of teacher.sex
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.sex
     *
     * @param sex the value for teacher.sex
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Create_time
     *
     * @return the value of teacher.Create_time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Create_time
     *
     * @param createTime the value for teacher.Create_time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Creator
     *
     * @return the value of teacher.Creator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Creator
     *
     * @param creator the value for teacher.Creator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Update_Time
     *
     * @return the value of teacher.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Update_Time
     *
     * @param updateTime the value for teacher.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Updator
     *
     * @return the value of teacher.Updator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Updator
     *
     * @param updator the value for teacher.Updator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }
}