package com.hbnu.mooc.bean;

public class TeacherCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachercourse.id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachercourse.teacher_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachercourse.course_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachercourse.id
     *
     * @return the value of teachercourse.id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachercourse.id
     *
     * @param id the value for teachercourse.id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachercourse.teacher_id
     *
     * @return the value of teachercourse.teacher_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachercourse.teacher_id
     *
     * @param teacherId the value for teachercourse.teacher_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachercourse.course_id
     *
     * @return the value of teachercourse.course_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachercourse.course_id
     *
     * @param courseId the value for teachercourse.course_id
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }
}