package com.hbnu.mooc.bean;

import java.util.Date;

public class Topic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.Topic_ID
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.Subject_ID
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.description
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.Create_time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.Creator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.Updator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    private String updator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.Topic_ID
     *
     * @return the value of topic.Topic_ID
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.Topic_ID
     *
     * @param topicId the value for topic.Topic_ID
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setTopicId(String topicId) {
        this.topicId = topicId == null ? null : topicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.Subject_ID
     *
     * @return the value of topic.Subject_ID
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.Subject_ID
     *
     * @param subjectId the value for topic.Subject_ID
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.description
     *
     * @return the value of topic.description
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.description
     *
     * @param description the value for topic.description
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.Create_time
     *
     * @return the value of topic.Create_time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.Create_time
     *
     * @param createTime the value for topic.Create_time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.Creator
     *
     * @return the value of topic.Creator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.Creator
     *
     * @param creator the value for topic.Creator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.Update_Time
     *
     * @return the value of topic.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.Update_Time
     *
     * @param updateTime the value for topic.Update_Time
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.Updator
     *
     * @return the value of topic.Updator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.Updator
     *
     * @param updator the value for topic.Updator
     *
     * @mbg.generated Thu Sep 20 16:18:00 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }
}