package com.hbnu.mooc.dao;

import com.hbnu.mooc.bean.course_exam;
import com.hbnu.mooc.bean.course_examExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface course_examMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_exam
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    long countByExample(course_examExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_exam
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int deleteByExample(course_examExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_exam
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int insert(course_exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_exam
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int insertSelective(course_exam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_exam
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    List<course_exam> selectByExample(course_examExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_exam
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") course_exam record, @Param("example") course_examExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_exam
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int updateByExample(@Param("record") course_exam record, @Param("example") course_examExample example);
}