package com.hbnu.mooc.dao;

import com.hbnu.mooc.bean.questiontype;
import com.hbnu.mooc.bean.questiontypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface questiontypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    long countByExample(questiontypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int deleteByExample(questiontypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int deleteByPrimaryKey(String typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int insert(questiontype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int insertSelective(questiontype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    List<questiontype> selectByExample(questiontypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    questiontype selectByPrimaryKey(String typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") questiontype record, @Param("example") questiontypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int updateByExample(@Param("record") questiontype record, @Param("example") questiontypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int updateByPrimaryKeySelective(questiontype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questiontype
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int updateByPrimaryKey(questiontype record);
}