package com.hbnu.mooc.dao;

import com.hbnu.mooc.bean.teachercourse;
import com.hbnu.mooc.bean.teachercourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface teachercourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    long countByExample(teachercourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int deleteByExample(teachercourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int insert(teachercourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int insertSelective(teachercourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    List<teachercourse> selectByExample(teachercourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") teachercourse record, @Param("example") teachercourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachercourse
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    int updateByExample(@Param("record") teachercourse record, @Param("example") teachercourseExample example);
}