package com.hbnu.mooc.bean;

import java.util.Date;

public class answer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answer_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String answerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.question_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.option_A
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String optionA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.option_B
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String optionB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.option_C
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String optionC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.option_D
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String optionD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.correct
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String correct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String updator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answer_id
     *
     * @return the value of answer.answer_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answer_id
     *
     * @param answerId the value for answer.answer_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setAnswerId(String answerId) {
        this.answerId = answerId == null ? null : answerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.question_id
     *
     * @return the value of answer.question_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.question_id
     *
     * @param questionId the value for answer.question_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId == null ? null : questionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.option_A
     *
     * @return the value of answer.option_A
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getOptionA() {
        return optionA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.option_A
     *
     * @param optionA the value for answer.option_A
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setOptionA(String optionA) {
        this.optionA = optionA == null ? null : optionA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.option_B
     *
     * @return the value of answer.option_B
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getOptionB() {
        return optionB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.option_B
     *
     * @param optionB the value for answer.option_B
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setOptionB(String optionB) {
        this.optionB = optionB == null ? null : optionB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.option_C
     *
     * @return the value of answer.option_C
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getOptionC() {
        return optionC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.option_C
     *
     * @param optionC the value for answer.option_C
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setOptionC(String optionC) {
        this.optionC = optionC == null ? null : optionC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.option_D
     *
     * @return the value of answer.option_D
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getOptionD() {
        return optionD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.option_D
     *
     * @param optionD the value for answer.option_D
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setOptionD(String optionD) {
        this.optionD = optionD == null ? null : optionD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.correct
     *
     * @return the value of answer.correct
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getCorrect() {
        return correct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.correct
     *
     * @param correct the value for answer.correct
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCorrect(String correct) {
        this.correct = correct == null ? null : correct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.Create_time
     *
     * @return the value of answer.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.Create_time
     *
     * @param createTime the value for answer.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.Creator
     *
     * @return the value of answer.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.Creator
     *
     * @param creator the value for answer.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.Update_Time
     *
     * @return the value of answer.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.Update_Time
     *
     * @param updateTime the value for answer.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.Updator
     *
     * @return the value of answer.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.Updator
     *
     * @param updator the value for answer.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }
}