package com.hbnu.mooc.bean;

public class class_course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_course.id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_course.course_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_course.Class_ID
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String classId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_course.id
     *
     * @return the value of class_course.id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_course.id
     *
     * @param id the value for class_course.id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_course.course_id
     *
     * @return the value of class_course.course_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_course.course_id
     *
     * @param courseId the value for class_course.course_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_course.Class_ID
     *
     * @return the value of class_course.Class_ID
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_course.Class_ID
     *
     * @param classId the value for class_course.Class_ID
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }
}