package com.hbnu.mooc.bean;

import java.util.Date;

public class course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String updator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Resource_Path
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String resourcePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Create_time
     *
     * @return the value of course.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Create_time
     *
     * @param createTime the value for course.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Creator
     *
     * @return the value of course.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Creator
     *
     * @param creator the value for course.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Update_Time
     *
     * @return the value of course.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Update_Time
     *
     * @param updateTime the value for course.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Updator
     *
     * @return the value of course.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Updator
     *
     * @param updator the value for course.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Resource_Path
     *
     * @return the value of course.Resource_Path
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getResourcePath() {
        return resourcePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Resource_Path
     *
     * @param resourcePath the value for course.Resource_Path
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setResourcePath(String resourcePath) {
        this.resourcePath = resourcePath == null ? null : resourcePath.trim();
    }
}