package com.hbnu.mooc.bean;

public class course_exam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_exam.id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_exam.course_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_exam.paper_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String paperId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_exam.id
     *
     * @return the value of course_exam.id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_exam.id
     *
     * @param id the value for course_exam.id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_exam.course_id
     *
     * @return the value of course_exam.course_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_exam.course_id
     *
     * @param courseId the value for course_exam.course_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_exam.paper_id
     *
     * @return the value of course_exam.paper_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_exam.paper_id
     *
     * @param paperId the value for course_exam.paper_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setPaperId(String paperId) {
        this.paperId = paperId == null ? null : paperId.trim();
    }
}