package com.hbnu.mooc.bean;

import java.util.Date;

public class grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String gradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.student_no
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String studentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.class_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.paper_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String paperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.subjective_score
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String subjectiveScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.objective_score
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String objectiveScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String updator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.Score
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade_id
     *
     * @return the value of grade.grade_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade_id
     *
     * @param gradeId the value for grade.grade_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setGradeId(String gradeId) {
        this.gradeId = gradeId == null ? null : gradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.student_no
     *
     * @return the value of grade.student_no
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.student_no
     *
     * @param studentNo the value for grade.student_no
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.class_id
     *
     * @return the value of grade.class_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.class_id
     *
     * @param classId the value for grade.class_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.paper_id
     *
     * @return the value of grade.paper_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.paper_id
     *
     * @param paperId the value for grade.paper_id
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setPaperId(String paperId) {
        this.paperId = paperId == null ? null : paperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.subjective_score
     *
     * @return the value of grade.subjective_score
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getSubjectiveScore() {
        return subjectiveScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.subjective_score
     *
     * @param subjectiveScore the value for grade.subjective_score
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setSubjectiveScore(String subjectiveScore) {
        this.subjectiveScore = subjectiveScore == null ? null : subjectiveScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.objective_score
     *
     * @return the value of grade.objective_score
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getObjectiveScore() {
        return objectiveScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.objective_score
     *
     * @param objectiveScore the value for grade.objective_score
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setObjectiveScore(String objectiveScore) {
        this.objectiveScore = objectiveScore == null ? null : objectiveScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.Create_time
     *
     * @return the value of grade.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.Create_time
     *
     * @param createTime the value for grade.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.Creator
     *
     * @return the value of grade.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.Creator
     *
     * @param creator the value for grade.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.Update_Time
     *
     * @return the value of grade.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.Update_Time
     *
     * @param updateTime the value for grade.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.Updator
     *
     * @return the value of grade.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.Updator
     *
     * @param updator the value for grade.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.Score
     *
     * @return the value of grade.Score
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.Score
     *
     * @param score the value for grade.Score
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }
}