package com.hbnu.mooc.bean;

import java.util.Date;

public class student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Student_NO
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String studentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.User_ID_s
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String userIdS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.College_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String collegeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Subject_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String subjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Class_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String updator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Student_NO
     *
     * @return the value of student.Student_NO
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Student_NO
     *
     * @param studentNo the value for student.Student_NO
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.User_ID_s
     *
     * @return the value of student.User_ID_s
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getUserIdS() {
        return userIdS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.User_ID_s
     *
     * @param userIdS the value for student.User_ID_s
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setUserIdS(String userIdS) {
        this.userIdS = userIdS == null ? null : userIdS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.College_Name
     *
     * @return the value of student.College_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.College_Name
     *
     * @param collegeName the value for student.College_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName == null ? null : collegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Subject_Name
     *
     * @return the value of student.Subject_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Subject_Name
     *
     * @param subjectName the value for student.Subject_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Class_Name
     *
     * @return the value of student.Class_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Class_Name
     *
     * @param className the value for student.Class_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Create_time
     *
     * @return the value of student.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Create_time
     *
     * @param createTime the value for student.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Creator
     *
     * @return the value of student.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Creator
     *
     * @param creator the value for student.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Update_Time
     *
     * @return the value of student.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Update_Time
     *
     * @param updateTime the value for student.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Updator
     *
     * @return the value of student.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Updator
     *
     * @param updator the value for student.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Name
     *
     * @return the value of student.Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Name
     *
     * @param name the value for student.Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}