package com.hbnu.mooc.bean;

import java.util.Date;

public class subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.Subject_ID
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.Subject_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String subjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    private String updator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.Subject_ID
     *
     * @return the value of subject.Subject_ID
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.Subject_ID
     *
     * @param subjectId the value for subject.Subject_ID
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.Subject_Name
     *
     * @return the value of subject.Subject_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.Subject_Name
     *
     * @param subjectName the value for subject.Subject_Name
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName == null ? null : subjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.Create_time
     *
     * @return the value of subject.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.Create_time
     *
     * @param createTime the value for subject.Create_time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.Creator
     *
     * @return the value of subject.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.Creator
     *
     * @param creator the value for subject.Creator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.Update_Time
     *
     * @return the value of subject.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.Update_Time
     *
     * @param updateTime the value for subject.Update_Time
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.Updator
     *
     * @return the value of subject.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.Updator
     *
     * @param updator the value for subject.Updator
     *
     * @mbg.generated Tue Sep 18 11:38:21 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }
}